version: 2.1

jobs:
    build:
        docker:
            - image: cimg/go:1.15
              environment:
                GOLANGCI_LINT_VER:  1.31.0
                PGUSER:             postgresuser
                PGPASSWORD:         postgrespass
                PGHOST:             localhost
                PGPORT:             5432
                PGDATABASE:         postgres
                PGSSLMODE:          disable
                NARADA4D_TEST_MYSQL: mysql://root@127.0.0.1:3306/gotest
            - image: "postgres:11.7"
              environment:
                POSTGRES_USER:      postgresuser
                POSTGRES_PASSWORD:  postgrespass
                POSTGRES_DB:        postgres
            - image: mysql:5.7
              environment:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
        steps:
            - checkout
            - run: env | grep _VER | sort > /tmp/tools.ver
            - restore_cache:
                keys:
                    - v3-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                    - v3-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-
                    - v3-{{ checksum "/tmp/tools.ver" }}-
            - run:
                name: Install tools
                command: |
                    cd /
                    golangci-lint --version | tee /dev/stderr | grep -wq $GOLANGCI_LINT_VER ||
                        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v$GOLANGCI_LINT_VER
                    which goveralls >/dev/null ||
                        go get -v github.com/mattn/goveralls
            - run: golangci-lint run
            - run: dockerize -timeout 30s -wait tcp://$PGHOST:$PGPORT -wait tcp://localhost:3306
            - run: go test -mod=readonly -v -race -tags=integration ./...
            - run: goveralls -service=circle-ci -flags -tags=integration
            - save_cache:
                when: always
                key: v3-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                paths:
                    - ~/go/bin/
                    - ~/go/pkg/
                    - ~/go/src/
                    - ~/.cache/go-build/
